version: '3.8'

services:
  mariadb:
    image: mariadb:inception
    container_name: mariadb
    init: true
    restart: on-failure
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    networks:
      - inception_nw
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    image: wordpress:inception
    container_name: wordpress
    init: true
    restart: on-failure
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    networks:
      - inception_nw
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb

  nginx:
    image: nginx:inception
    init: true
    container_name: nginx
    restart: on-failure
    build:
      context: ./requirements/nginx
    networks:
      - inception_nw
    ports:
      - 443:443
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

networks:
  inception_nw:
    name: inception_nw
    driver: bridge

volumes:
  mariadb:
    driver_opts:
      o: bind
      type: none
      device: /home/${LOGIN}/data/mariadb
  wordpress:
    driver_opts:
      o: bind
      type: none
      device: /home/${LOGIN}/data/wordpress
